# Generated by Django 5.1 on 2024-09-01 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDetails',
            fields=[
                ('bldg_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'facility_details',
            },
        ),
        migrations.CreateModel(
            name='DisposalDetails',
            fields=[
                ('shipment_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sender_approval', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('receiver_approval', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('disposal_confirmation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
            ],
            options={
                'db_table': 'disposal_details',
                'constraints': [models.CheckConstraint(condition=models.Q(('shipment_no__startswith', 'SH')), name='shipment_no_starts_with_SH')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=20)),
                ('bldg_no', models.ForeignKey(db_column='bldg_no', on_delete=django.db.models.deletion.CASCADE, to='webapp.facilitydetails')),
            ],
            options={
                'db_table': 'user',
                'constraints': [models.CheckConstraint(condition=models.Q(('user_id__startswith', 'U')), name='user_id_starts_with_U')],
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('sl_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('waste_type', models.CharField(choices=[('A', 'Type A'), ('B', 'Type B'), ('C', 'Type C'), ('D', 'Type D'), ('E', 'Type E')], max_length=1)),
                ('bldg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.facilitydetails')),
            ],
            options={
                'db_table': 'waste_type',
                'constraints': [models.CheckConstraint(condition=models.Q(('sl_no__startswith', 'S')), name='sl_no_starts_with_S')],
            },
        ),
    ]
