# Generated by Django 5.1 on 2024-08-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_code', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('facility', models.CharField(max_length=20)),
            ],
        ),
    ]
