# Generated by Django 5.1 on 2024-09-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('request_no', models.IntegerField(primary_key=True, serialize=False)),
                ('sm_remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('rm_remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
