# Generated by Django 5.1 on 2024-08-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
    ]
